language: php

php:
 # - 5.3
 - 5.4
 # - 5.5

env:
 # - SYMFONY_VERSION=2.3.*
 - SYMFONY_VERSION=dev-master

before_script:
 # - composer install -n
 # - composer require symfony/http-foundation:${SYMFONY_VERSION}
 - wget http://getcomposer.org/composer.phar

 - ./bin/install-apcu.sh
 - php composer.phar install --dev --no-interaction

script:
 # - phpunit -c app
 # - bin/atoum --test-all

 # - mkdir -p build/logs
 # - phpunit --coverage-clover build/logs/clover.xml

 # - phpunit -c app --coverage-clover app/cache/test/clover.xml
  - phpunit -c app --coverage-clover app/logs/clover.xml

after_script:
 - php bin/coveralls -v

#after_failure: "cat /home/travis/builds/rek/Rotes/npm-debug.log"