parameters:
    rek.rotes.class: REK\RotesBundle\Form\Type\RoteType
    rek.rotes.admin.class: REK\RotesBundle\Form\Type\RoteCreateType

services:
    rotes.form.type.rote:
        class: "%rek.rotes.class%"
        tags:
            - { name: form.type, alias: rote }
        # need a session?
        # arguments:
            # session: @session
    rotes.form.type.rote.admin:
        class: "%rek.rotes.admin.class%"
        tags:
            - { name: form.type, alias: roteadmin }
